ah_dc            = "ams1"
ah_token         = "YOUR-TOKEN"
ah_machine_type  = "start-xs"
ah_image_type    = "centos-7-x64"
private_key_path = "/home/alex/.ssh/id_rsa.pub"
type             = "public"
use_password     = "true"
